stages:
    - test
    - build
    - deploy

unit-test:
    script: "D:/Program Files/Unity/Hub/Editor/2020.3.18f1/Editor/Unity.exe \
        -batchmode \
        -projectPath . \
        -runTests -testPlatform playmode \
        -logFile - \
        -testResults ./unit-tests.xml
        | Out-Default"
    after_script:
        - '[xml]$xml = Get-Content -PATH ./unit-tests.xml'
        - '$xml.SelectNodes("//test-case") | Format-Table -AutoSize -Property result, name'
    stage: test
    tags:
        - unity

unity-build:
    script: "echo 'Building...'"
    stage: build
    tags:
        - unity

playstore:
    script: "echo 'Deploying...'"
    stage: deploy
    tags:
        - unity
